"""collaboration knowledge retention evidence

Revision ID: ab1ec74d40fb
Revises: 99bc48c4d9fa
Create Date: 2026-07-31 04:33:18.463712
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'ab1ec74d40fb'
down_revision: Union[str, None] = '99bc48c4d9fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('process_module', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=True),
    sa.Column('prospect_id', sa.String(length=36), nullable=True),
    sa.Column('classification', sa.String(length=30), nullable=False),
    sa.Column('reusable_across_prospects', sa.Boolean(), nullable=False),
    sa.Column('approval_state', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entries_capability_id'), 'knowledge_entries', ['capability_id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_process_module'), 'knowledge_entries', ['process_module'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_prospect_id'), 'knowledge_entries', ['prospect_id'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_source_type'), 'knowledge_entries', ['source_type'], unique=False)
    op.add_column('evidence_items', sa.Column('extraction_state', sa.String(length=30), server_default='NOT_APPLICABLE', nullable=False))
    op.add_column('evidence_items', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('evidence_items', sa.Column('ai_inclusion_recommendation', sa.JSON(), nullable=True))
    op.add_column('prospects', sa.Column('archive_prompted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prospects', sa.Column('last_exported_at', sa.DateTime(timezone=True), nullable=True))
    with op.batch_alter_table('report_sections') as batch_op:
        batch_op.add_column(sa.Column('assigned_to_user_id', sa.String(length=36), nullable=True))
        batch_op.create_index(op.f('ix_report_sections_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_foreign_key('fk_report_sections_assigned_to_user', 'users', ['assigned_to_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_sections') as batch_op:
        batch_op.drop_constraint('fk_report_sections_assigned_to_user', type_='foreignkey')
        batch_op.drop_index(op.f('ix_report_sections_assigned_to_user_id'))
        batch_op.drop_column('assigned_to_user_id')
    op.drop_column('prospects', 'last_exported_at')
    op.drop_column('prospects', 'archive_prompted_at')
    op.drop_column('evidence_items', 'ai_inclusion_recommendation')
    op.drop_column('evidence_items', 'extracted_text')
    op.drop_column('evidence_items', 'extraction_state')
    op.drop_index(op.f('ix_knowledge_entries_source_type'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_prospect_id'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_process_module'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_capability_id'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    # ### end Alembic commands ###
